import Vue from 'vue';
import {
    Tabbar,
    TabbarItem,
    NavBar,
    Button,
    Swipe,
    SwipeItem,
    Lazyload,
    Form,
    Field,
    Notify,
    Toast,
    Popup,
    ImagePreview,
    Icon,
    Search,
    Tag,
    Tabs,
    Tab,
    Loading,
    Cell,
    CellGroup,
    GridItem,
    Grid,
    NoticeBar,
    List,
    Image,
    Divider,
    Collapse,
    CollapseItem,
    Picker,
    DatetimePicker,
    Uploader
} from 'vant';
Vue.use(Tabbar)
    .use(Uploader)
    .use(TabbarItem)
    .use(Button)
    .use(DatetimePicker)
    .use(NavBar)
    .use(Collapse)
    .use(CollapseItem)
    .use(Picker)
    .use(Swipe)
    .use(SwipeItem)
    .use(Lazyload)
    .use(Form)
    .use(Notify)
    .use(Icon)
    .use(Field)
    .use(Toast)
    .use(Popup)
    .use(Loading)
    .use(ImagePreview)
    .use(Search)
    .use(Tabs)
    .use(Tab)
    .use(Tag)
    .use(Cell)
    .use(CellGroup)
    .use(Grid)
    .use(GridItem)
    .use(NoticeBar)
    .use(List)
    .use(Image)
    .use(Divider);
